language: ruby

rvm:
- 2.3.1
before_install:
  - sed -i '2d' Gemfile
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.3

script: bundle exec rspec spec

before_script:
  - psql -c 'create database makersbnb_test;' -U postgres
